### PR TITLE
new kernel with overlayFS

### PR DESCRIPTION
**Pull request by chrismade**
now there is a kernel with overlayFS support - which is required for Volumio2 Build -
and SPDIF out support

### CODE REVIEW

**Comment by volumio** [comment]
Did you tested it? Does it boot properly?

**Comment by chrismade** [comment]
yes, it is tested and volumio2 is booting properly till login and stable operations with this kernel on a banana pi pro - but I noticed that gkkpch has also created a build script - so I will check this work first before I make any further pull request to the build scripts

**Comment by volumio** [comment]
Thanks, I believe that @gkkpch kernel was the armbian one. 
Does yours include support for i2s ?

**Comment by chrismade** [comment]
i2s support - I think so but not yet tested - my prio was trying to find a kernel for SPDIF (up to 3.4.x and then added from 4.7.x on) and overlayFS (special effort needed in any 3.x) -

**Comment by gkkpch** [comment]
@chrismade: which kernel version is yours? Did you need to make any changes to initrd (overlayfs version)? 
Mine is based on the 3.4.104 version they use for armbian.
I used overlayfs.v13-3.4-rc7.patch from adlinden.

**Comment by chrismade** [comment]
@gkkpch my kernel is 3.4.113 based on bananian - overlay patch is exactly the same as yours - you can download and try from my fork - I'm currently checking your build skripts

**Comment by gkkpch** [comment]
There are only a few things we really need, as many popular wifi drivers we can have and overlayfs.
We don't need armbian, I just trusted the armbian guys because of their reputation.
If the bananian kernel is equally good, then go for it. I have not checked in mine anyway, and as it seems bpi-m2u is a dead end...
Nice to get more help from platform builders. Makes Volumio better and better! :)

**Pull request merged**
